import type { Metadata } from "next";

export const siteUrl = "https://bluegrassadvisorygroup.com";
const brand = "Bluegrass Advisory Group";

// The site-wide OG card is generated by src/app/opengraph-image.tsx.
// Next replaces the whole `openGraph` / `twitter` object when a page sets one,
// so every page-level object below has to carry the image itself.
const ogImages = [
  {
    url: "/opengraph-image",
    width: 1200,
    height: 630,
    alt: "Bluegrass Advisory Group. AI systems for Kentucky businesses, Lexington, Kentucky.",
  },
];

export const siteMetadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "Bluegrass Advisory Group: AI Systems for Kentucky Businesses",
    template: "%s | Bluegrass Advisory Group",
  },
  description:
    "AI systems, dashboards, websites and operations consulting for Kentucky businesses, from Phil Fifield in Lexington, KY.",
  keywords: [
    "AI consulting",
    "AI consulting Kentucky",
    "AI consulting Lexington KY",
    "business operations consulting",
    "small business AI",
    "web design Lexington KY",
    "dashboard development",
    "business automation Kentucky",
  ],
  authors: [{ name: "Phil Fifield", url: siteUrl }],
  creator: brand,
  // ponytail: no canonical here on purpose. A root canonical is inherited by every
  // page that does not set one, which pointed /contact at the homepage. Each page
  // sets its own through pageMeta().
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: brand,
    title: "Bluegrass Advisory Group: AI Systems for Kentucky Businesses",
    description:
      "AI systems, dashboards, websites and operations consulting for Kentucky businesses. Lexington, Kentucky.",
    images: ogImages,
  },
  twitter: {
    card: "summary_large_image",
    title: brand,
    description: "AI systems for Kentucky businesses. Lexington, KY.",
    images: ogImages,
  },
  robots: {
    index: true,
    follow: true,
  },
};

interface PageMetaInput {
  /** Page title without the brand suffix. The layout template appends it. */
  title: string;
  description: string;
  /** Root-relative path, e.g. "/services/dashboards". */
  path: string;
  /** Set for blog posts. */
  article?: { publishedTime: string };
}

/**
 * Full per-page metadata: title, description, canonical, and complete
 * openGraph + twitter objects. Complete matters: a partial object drops the
 * inherited image and the summary_large_image card.
 */
export function pageMeta({
  title,
  description,
  path,
  article,
}: PageMetaInput): Metadata {
  const socialTitle = `${title} | ${brand}`;
  const shared = {
    locale: "en_US" as const,
    url: `${siteUrl}${path}`,
    siteName: brand,
    title: socialTitle,
    description,
    images: ogImages,
  };

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: article
      ? { ...shared, type: "article", publishedTime: article.publishedTime }
      : { ...shared, type: "website" },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: ogImages,
    },
  };
}
